name       : khtml
version    : 5.79.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/portingAids/khtml-5.79.0.tar.xz : 1ece8dbd1bae528e07a335ef53278b8fda3e79a6c52ce0163d0de439d69d26a4
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - pkgconfig(x11)
    - giflib-devel
    - gperf
    - karchive-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
