name       : khtml
version    : 5.36.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.36/portingAids/khtml-5.36.0.tar.xz : fad99c7f46f4ad932300d0ad9dafeb9b18fc32de05efa937e9df0f7b138c5395
license    :
    - GPL-3.0
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - giflib-devel
    - gperf
    - karchive-devel
    - kcodecs-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libjpeg-turbo-devel
    - libpng-devel
rundeps    :
    - devel :
        - kcodecs-devel
        - ki18n-devel
        - kio-devel
        - kjs-devel
        - kparts-devel
        - ktextwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
