name       : khtml
version    : 5.100.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/portingAids/khtml-5.100.0.tar.xz : 40a5cd6e3a5db5310bca59ccb7a6cbf70f3f45b1a3db9b933882390f6c581c41
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - pkgconfig(x11)
    - giflib-devel
    - gperf
    - karchive-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
