name       : khtml
version    : 5.76.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/portingAids/khtml-5.76.0.tar.xz : 163139cf9ed9c43bba9532e64ae6376e8ced9b19ea8bb8235ff91c91c4c5a3f4
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - giflib-devel
    - gperf
    - karchive-devel
    - kcodecs-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kcodecs-devel
        - ki18n-devel
        - kio-devel
        - kjs-devel
        - kparts-devel
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
