name       : khtml
version    : 5.57.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/portingAids/khtml-5.57.0.tar.xz : 63d22fbc8cad3075a0b7ef195291c4b79ebc65da5de81b4885cac1063d783da3
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - extra-cmake-modules
    - giflib-devel
    - gperf
    - karchive-devel
    - kcodecs-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kcodecs-devel
        - ki18n-devel
        - kio-devel
        - kjs-devel
        - kparts-devel
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
