name       : khtml
version    : 5.82.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/portingAids/khtml-5.82.0.tar.xz : 0d731761778a9908883353e3b9d9d89dda573c3aca4a9ad447277a280215af2d
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - pkgconfig(x11)
    - giflib-devel
    - gperf
    - karchive-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
