name       : khtml
version    : 5.101.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.101/portingAids/khtml-5.101.0.tar.xz : 8826da7bcff3d28ee711e3941d1f0fd0bbdb53a6e325f7727837a1432b7afcf5
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - pkgconfig(x11)
    - giflib-devel
    - gperf
    - karchive-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
