name       : khtml
version    : 5.64.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/portingAids/khtml-5.64.0.tar.xz : 00d3a3e8c8b8072f4894d74f91d963cfefbd681e47da0b8e80e1297224c5af85
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - extra-cmake-modules
    - giflib-devel
    - gperf
    - karchive-devel
    - kcodecs-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kcodecs-devel
        - ki18n-devel
        - kio-devel
        - kjs-devel
        - kparts-devel
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
