name       : khtml
version    : 5.107.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/portingAids/khtml-5.107.0.tar.xz : 3b4597da6f28257cba8381283f8218ab7a83bbac1418a8926180597460d195fd
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - pkgconfig(x11)
    - giflib-devel
    - gperf
    - karchive-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
