name       : khtml
version    : 5.48.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/portingAids/khtml-5.48.0.tar.xz : a1923402f04f4a72e8688004a00e47fe79f7f72d703d53a14058eebdb7a531ff
license    :
    - GPL-3.0
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : KDE Web Rendering Engine
description: |
    KHTML is a web rendering engine, based on the KParts technology and using KJS for JavaScript support.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(gl)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(phonon4qt5)
    - extra-cmake-modules
    - giflib-devel
    - gperf
    - karchive-devel
    - kcodecs-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjs-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kcodecs-devel
        - ki18n-devel
        - kio-devel
        - kjs-devel
        - kparts-devel
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
